---
name: working_groups
full_name: Working Group Working Group
type: docs
owner_type: "working-group"
status: paused
testable: false
description: >
  We create an environment in which working groups and guilds can thrive and have a meaningful impact on 18F deliverables and operations.
stage: live
licenses:
  wg-working_groups:
    name: Public Domain (CC0)
    url: https://creativecommons.org/publicdomain/zero/1.0/ 
links:
- url: https://pages.18f.gov/wg-working_groups/
  text: 18F Working Group Working Group home page
team:
- github: gbinal
  role: lead
- github: nickbristow
- github: brethauer
